# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# DON'T TELL ME WHAT TO DO

{ config, lib, pkgs, ... }: {
  imports = [ ];

  boot = {
    initrd = {
      availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
      kernelModules = [ "vfat" "nls_cp437" "nls_iso8859-1" "usbhid" "dm-snapshot" ];
      luks = {
        cryptoModules = [ "aes" "xts" "sha512" ];
        yubikeysupport = true;
        devices = [ {
          name = "nixos";
          device = "/dev/disk/by-partlabel/nixos";
          preLVM = true;
          yubikey = {
            slot = 2;
            twoFactor = true;
            storage = {
              device = "/dev/disk/by-label/boot";
            };
          };
        } ];
      };
    };
    kernelModules = [ "kvm-amd" "kvm-intel" ];
    extraModulePackages = [ ];

    enableContainers = true;
    # Use the systemd-boot EFI boot loader.
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };


  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/root";
      fsType = "btrfs";
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  };

  swapDevices = [{ device = "/dev/disk/by-label/swap"; }];

  nix.maxJobs = lib.mkDefault 4;
}
