# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot =
    {
      initrd =
        {
          availableKernelModules = [
            "xhci_pci"
            "ahci"
            "nvme"
            "usb_storage"
            "sd_mod"
            "sdhci_pci"
          ];
          kernelModules = [ "dm-snapshot" ];
        };
      kernelModules = [ "kvm-intel" ];
      extraModulePackages = [ ];
    };

  fileSystems =
    {
      "/" = {
        device = "/dev/disk/by-label/fsroot";
        fsType = "btrfs";
        options = [ "subvol=nixos" ];
      };
      "/home" = {
        device = "/dev/disk/by-label/fsroot";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };
      "/nix" = {
        device = "/dev/disk/by-label/fsroot";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };
      "/boot" =
        {
          device = "/dev/disk/by-label/boot";
          fsType = "vfat";
        };
    };
  swapDevices =
    [{ device = "/dev/disk/by-label/swap"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
