# ext4-filesystem.nix
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
#  and may be overwritten by future invocations.  Please make changes
#  to /etc/nixos/configuration.nix instead.
#
# I Refuse

{ config, lib, pkgs, ... }: {

  boot = {
    initrd = {
      availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  };

  swapDevices = [ {
    device = "/dev/disk/by-label/swap";
  } ];

  nix.maxJobs = lib.mkDefault 4;
}
